sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/ant-node
  - secure: Hr/b9LH/p2QI3QOyaaYnZDesm75TSxjWUyUIFlZJD8YWuCSSOoscMDdFf5OTWa0DiqlSxHiYy5LSdtlayh1tcFZxJ+N41+DsjohvCBM3KyCuLoPNNAIsKZ/wW8cSPQXbs5eiA0UbG/ssVphZZQVnvWj5ATFDDZP5kwYd9h5eBhO/dAOGU5MSY1hTg0Bgp1qHEFfZFUIbRb1F/mXzZ229NiFvoryyMrXXmBw25WO9hMTm1xkKqPk09ELe531xiYpSgWv/BMFsDICOrmXYElGAi6v9ZAHc9QiHOWW/8stUtFz9FQhRcD/LoVK973duqxKzohzk6HYPgbj47UFkMBbegP0I82zLBqiSTi1wGk79PWfoz77KicCJAgfLbWu9TlCMQjDPGqt1/d3EltKMaQY8r5wrYywciAg87lCfNzio+h14EV+4JCm9wkbyOy7v741AWPiIxeeoNKPBOOTjM7Rs8OEOmlPU/m7x3zB5zzOLM302/XqYdTDWRRMUZg/HqjjiG2cznq5RtkmJJRUrYrE3kv5PcmUA5JWfI1U5kCy8zpDi0Q05LMW09dmlHyqcnUbdYzcAkKVOF6Vm9wFNU6MIF6BQIe6TxHeBnhqPsqfTbo7f7H3B3uZf8mdxA9ao54WNe2TCt7islRxLWlM+mjlwC1qSXxQZme3OKRxG23QUO64=
  - secure: IuoFrwxL+Kab/uL/cY9YFpcNecDct8hR/ZQl0LYLFBoubZjzpO+eAWbyosQH7Mz7+R2SMUk6+tonJBrP99ihtSaJUpADGbuhMCpdtqUZ3Y3EBmVH9PeCsqsTMrPaMCVMYMrpP1dNcljHAWRIlQTyk5dNjn9TU2rgIEmOqEJ5dc1JbYvVvEQoZyn6BJuqMmeWkySa1tZfq83zxKcq+Cc1OCVAsOwV3ZsooRYsgGqZFR278OJUubCMCNvuv+uyICKtH4s+Xa6TF9HQnNWF0EJxePC/Mdx+UQkPfmmULdTMK2J9OApuT6Jnu+4PcoqLoQcVMhRi3gwj5fMWy2mSjurX2BP8umQ5HApG4rQZgdI2ThRDVi1f2JSmrX3ySO0u+iU0xgpI01ELW+4JiJlmenGoafrwDrtDKuKui4EjYyQ71NvcqRKezHNcSKq3FpukBlFAZdkuR6iFnPnnLQsaX2BjwaXMu+sqxyHWDwBut3PdxmY6NAuqIkFyEMA+cg2Kz92fCb6DgDgNsaBmlf4Nt35jJ1AqhWsDzTSwhTZPHplpJPin2wrKfTNNDY9WniFsW8Uks/8tpSRpAaD5PwK4n1ZqCytW8tVYCTSgUyako2Heq/XlQLrKkIwSOib7/7nogS8JERcxKlUPTYvYVWgXmQ0WNofqsDCWZPBdo/tZ1sInRrY=
before_script:
- cd image
- version="$(awk -F ' '  '/ENV NODE_VERSION/ {print $3}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master